### ISSUE TITLE
Closing any Window in Graphstudio will automatically close any Video Renderer.

### ISSUE THREAD

**Issue by Zerowalker** [cplussharp/graph-studio-next#293] opened 2016-06-26 17:23 UTC
As topic says, not sure why this happens, but it's very frustrating cause i don't know how to open up the renderer again.

So if i record and render at the same time, i will have to starta a new recording in order to open the renderer again:(

Can this be prevented or solve in anyway?

**Comment by mikecopperwhite** [comment] 2016-08-04 19:56
Thanks for the report. However I'm unable to reproduce this by rendering a video media file and closing various property or floating windows during playback. I've probably misunderstood your problem report.

Can you give more specific steps to reproduce, please - e.g. rendering a standard built a standard sample media file like Wildlife.wmv and which video renderer filter you are using - supplying a GRF, GRFX and PNG of the graph with specific steps would be ideal. 

Closing the video renderer window during playback will terminate playback but I believe that's standard Video Render behaviour rather than anything GSN is doing.

Thanks.

**Closed** 2017-01-26 01:51 UTC
