### ISSUE TITLE
totally unusable at 288 DPI

### ISSUE THREAD

**Issue by stax76** [cplussharp/graph-studio-next#316] opened 2017-06-09 08:08 UTC
![unbenannt](https://user-images.githubusercontent.com/11410540/26966730-9d553bf0-4cfb-11e7-8e25-37cf47a19482.png)

**Comment by mikecopperwhite** [comment] 2017-06-11 12:28
Thanks for the report.

Sadly this is true. It's pretty hard to use at 200dpi too, in my experience. The original GraphStudio code is fully of pixel oriented sizing and positioning and assumptions about pixel font dimensions. Rewriting all of this is a very big job but we could improve the worst areas.

Clearly the filters dialog you've posted is particularly bad. Are there other parts of the app that are unusable rather than just ugly?

**Comment by stax76** [comment] 2017-07-07 13:48
Thanks for the reply. I've not used many other dialogs. In the main dialog pin knobs and toolbar buttons are very very small.

**Comment by mikecopperwhite** [comment] 2019-02-28 11:28
Duplicate of issue #255

**Closed by mikecopperwhite** 2019-02-28 11:28 UTC
Labels: Component-UI

**Comment by mikecopperwhite** [comment] 2019-03-01 16:44
Closed as duplicate of #255 but feel free to add further comments on that bug report.

**Comment by mikecopperwhite** [comment] 2019-03-04 15:11
Some significant improvements to filters window checked in. More fixes required.
